server:
  port: 80
jwt:
  secret: Key#SuperSecret$Aforo2SS#JavaMicroservices#987654321
spring:
  application:
    name: appgateway
  zipkin:
    base-url: http://service-tracer:9411
  cloud:
    gateway:
      default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:      
      - id: appsecurity
        uri: http://app-security:80
        predicates:
          - Path=/security/**
        filters:
          - StripPrefix=1
      - id: appaccount
        uri: http://app-account:80
        predicates:
          - Path=/account/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
      - id: appdeposit
        uri: http://app-deposit:80
        predicates:
          - Path=/deposit/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
      - id: appwithdrawal
        uri: http://app-withdrawal:80
        predicates:
          - Path=/withdrawal/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
      - id: appmovement
        uri: http://app-movement:80
        predicates:
          - Path=/movement/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter
              
#Environment
environment:
    name:
        app: docker
